# Generated by Django 6.0.4 on 2026-06-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_security_hardening'),
        ('app', '0005_transfer_sender_card_fk_receiver_card_fk'),
    ]

    operations = [
    ]
